Repository ssuperpower-developer/design-pattern-study, pull requests merged in 2024-06, with the labels that each got.

#8 [1주차] 옵저버 패턴
  .gitignore
  Behavioral Pattern/Observer.md
  Behaviroal Pattern/Observer/Observer.md
  Behaviroal Pattern/Observer/weatherobservable/CurrentConditionsDisplay.java
  Behaviroal Pattern/Observer/weatherobservable/DisplayElement.java
  Behaviroal Pattern/Observer/weatherobservable/ForecastDisplay.java
  Behaviroal Pattern/Observer/weatherobservable/HeatIndexDisplay.java
  Behaviroal Pattern/Observer/weatherobservable/StatisticsDisplay.java
  Behaviroal Pattern/Observer/weatherobservable/WeatherData.java
  Behaviroal Pattern/Observer/weatherobservable/WeatherStation.java
  Behaviroal Pattern/Observer/weatherobservable/WeatherStationHeatIndex.java
Labels: 행동 패턴

#9 [1주차] : 전략 패턴
  .gitignore
  Behavioral Pattern/strategy/Strategy Pattern.md
  Behavioral Pattern/strategy/img/Pasted image 20240528204035.png
  Behavioral Pattern/strategy/img/Pasted image 20240528204539.png
  Behavioral Pattern/strategy/img/Pasted image 20240528204831.png
  Behavioral Pattern/strategy/img/Pasted image 20240528222251.png
  Behavioral Pattern/strategy/img/Pasted image 20240528222400.png
  README.md
Labels: 행동 패턴

#10 [1주차] builder 패턴
  Creatinal Pattern/Builder.md
  General/Design-pattern.md
  General/OOP.md
Labels: 생성 패턴

#11 [1주차] 팩토리 메소드 패턴
  Creatinal Pattern/Factory method.md
Labels: 생성 패턴

#14 [2주차] 프로토타입 패턴
  Creatinal Pattern/Prototype/Prototype.md
  Creatinal Pattern/Prototype/PrototypePattern/README.md
  Creatinal Pattern/Prototype/PrototypePattern/bin/Employees.class
  Creatinal Pattern/Prototype/PrototypePattern/bin/PrototypePatternTest.class
  Creatinal Pattern/Prototype/PrototypePattern/src/Employees.java
  Creatinal Pattern/Prototype/PrototypePattern/src/PrototypePatternTest.java
Labels: 생성 패턴

#20 [2주차] 싱글톤 패턴
  Creatinal Pattern/Singleton.md
Labels: 생성 패턴

#16 [2주차] proxy 패턴
  .gitignore
  Structural Pattern/proxy/img/Pasted image 20240618200513.png
  Structural Pattern/proxy/img/Pasted image 20240618211018.png
  Structural Pattern/proxy/proxy 패턴.md
Labels: 구조 패턴
